### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by KudMath** [meteor-helium/accounts-amazon#1]
Hi, I'm trying t login to amazon, and I'm not getting anywhere. Is your package usable? i don't seem to be getting anywhere with it...

**Comment by butane** [comment]
Yes, the package is tested and usable. Please post details about issue faced by you for further help.

**Comment by KudMath** [comment]
I setup my service configuration as I would for a facebook oauth but the amazon login flow sends an error client_id undefined. How do you setup your client id & secret properly? do you have a working exemple?

**Comment by butane** [comment]
Follow instructions on the [README.md](https://github.com/meteor-helium/accounts-amazon/blob/master/README.md) file. A "Configure Amazon Login" button will appear. Clicking the button will open a popup with details for generating the Client Id and Client secret and text boxes to paste them and save the configuration.

or alternatively..

You can directly create an entry in the "meteor_accounts_loginServiceConfiguration" collection with the following fields.

```
"service": "amazon",
"clientId": "your-client-id",
"clientSecret" : "your-client-secret",
"loginStyle" : "popup"
```

**Comment by KudMath** [comment]
Ok that works, I was using service config but I had "client_id" instead of "clientId" since that was what the popup was asking for. Thanks a lot for your help :)
